### ISSUE TITLE
Prediction Patient Definition

### ISSUE THREAD

**Issue by codyemoffitt** [arpachuilo/nemo#20]
Need to be able to define a patient to make predictions on in the Question Creator.

Automatically figure out which attributes are needed to define the patient (see Attribute-Selection on web-app issue).

Display appropriate inputs for each attribute (numeric textboxes, dropdowns)

Save the patient as a JSON attached to the question in the db:
Example: {age_in_years: 80, race_cd: "white", ..., '401.9start_date': '11/20/1987', ...}

One issue I can see coming up is that each non-numeric value must exist in the given dataset. Like if you  had a question that involved all black people with 401.9, and your example patient was 'white', the ARFF header generated by the query builder wouldn't include 'white' as a possible value, and would crash when you tried to predict. Need to find a way to fix this or around this.
Possible solution: Add the prediction patient to the all patient set in the wrapper, so the ARFF includes that patient's unique attributes.

**Comment by arpachuilo** [comment]
done
