### ISSUE TITLE
Ensemble Learning

### ISSUE THREAD

**Issue by codyemoffitt** [arpachuilo/nemo#22]
Need to implement ensemble learning. Not sure how to do it yet.

This might be helpful reading material: 
http://weka.sourceforge.net/doc.dev/weka/classifiers/meta/RandomCommittee.html
http://weka.sourceforge.net/doc.dev/weka/classifiers/meta/Stacking.html
http://weka.sourceforge.net/doc.dev/weka/classifiers/meta/Vote.html

**Comment by arpachuilo** [comment]
done
