### ISSUE TITLE
Editing Questions

### ISSUE THREAD

**Issue by masterRevillo** [arpachuilo/nemo#26]
We have yet to implement "User edits question" into the NEMO system. The code for this has been written, and is currently in the database_api.js file. I dont believe it has been moved to nemoApi.js yet. From what I remember, this function is supposed to retrieve the information of the corresponding question, display this info on the question creation page, and then allow the user to make changes to the question parameters. I believe the original question will be deleted after the question is edited. There were a couple questions I had on this:
- Will the deletion process be done by calling 'delete question'? If it is, when will that take place? Will there be a cancel feature?
- If editing the question takes the user to the question creation page with boxes already filled out, will submitting the question actually get done by 'create question'?
- A potential problem that could arise with this is what to do if the question is currently running on an algorithm. Do we have a safeguard against that yet?

**Comment by oopayne** [comment]
A designated editQuestion function should not be needed to complete this requirement. When the user selects a question, they will be asked if they would like to keep the original question. The old question is then loaded into the question creation page with the forms filled out. The user can then add or remove parameters. Once they submit the question, createQuestion is called with the new data. If the user selected to delete the old question, deleteQuestion is called (either before the new question is submitted or afterwards. Im not sure what would be best).

How does this sound?
